//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caja
    {
        public int CAJ_Id { get; set; }
        public Nullable<int> CLI_Id { get; set; }
        public long OT_Id { get; set; }
        public Nullable<short> CAJ_Esta { get; set; }
        public Nullable<short> CAJ_Fila { get; set; }
        public Nullable<short> CAJ_Colu { get; set; }
        public string CAJ_Prec1 { get; set; }
        public string CAJ_Prec2 { get; set; }
        public Nullable<short> CCO_Id { get; set; }
        public Nullable<short> DEP_Id { get; set; }
        public Nullable<short> TAM_Id { get; set; }
        public Nullable<bool> CAJ_Guarda { get; set; }
        public Nullable<bool> CAJ_Stickers { get; set; }
        public Nullable<bool> CAJ_Especial { get; set; }
        public Nullable<bool> CAJ_Ubicada { get; set; }
        public Nullable<bool> CAJ_Consultada { get; set; }
        public string Tipo_Mov { get; set; }
        public string usr_mov { get; set; }
        public Nullable<System.DateTime> CAJ_FecCarga { get; set; }
        public bool Caj_Grande { get; set; }
    }
}
