//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clasificada
    {
        public int CAJ_Id { get; set; }
        public int CLA_SubCaja { get; set; }
        public Nullable<int> TEM_Id { get; set; }
        public Nullable<int> STE_Id { get; set; }
        public Nullable<int> SST_Id { get; set; }
        public Nullable<System.DateTime> CLA_FecDe { get; set; }
        public Nullable<System.DateTime> CLA_FecHa { get; set; }
        public string CLA_LetDe { get; set; }
        public string CLA_LetHa { get; set; }
        public string CLA_NroDe { get; set; }
        public string CLA_NroHa { get; set; }
        public Nullable<System.DateTime> CLA_FecVe { get; set; }
        public string CLA_Observa { get; set; }
        public string TIPO_Mov { get; set; }
        public string USR_Mov { get; set; }
        public Nullable<int> cli_id { get; set; }
        public string caj_prec1 { get; set; }
        public string caj_prec2 { get; set; }
    }
}
