//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioCaja
    {
        public int CAJ_Id { get; set; }
        public bool Retirado { get; set; }
        public System.DateTime FechaCarga { get; set; }
        public int Id { get; set; }
    }
}
