//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullProgram
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ROGGIO2Entities : DbContext
    {
        public ROGGIO2Entities()
            : base("name=ROGGIO2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Caja> Cajas { get; set; }
        public virtual DbSet<Clasificada> Clasificadas { get; set; }
        public virtual DbSet<InventarioCaja> InventarioCajas { get; set; }
    }
}
